java_import(
    name = "proto",
    jars = [
        "jars/libdeps_proto-speed.jar",
        "jars/libworker_protocol_proto-speed.jar"
    ],
    exports = ["@io_bazel_rules_kotlin_protobuf_protobuf_java//jar"],
    visibility = ["//kotlin/workers:__subpackages__"]
)