java_library(
    name = "lib",
    srcs= glob(["**/*.java"]),
    visibility = ["//kotlin/workers:__subpackages__"],
    deps = [
        "@io_bazel_rules_kotlin_protobuf_protobuf_java//jar"
    ],
)

