load("@io_bazel_integration_testing//tools:bazel_java_integration_test.bzl", "bazel_java_integration_test")

bazel_java_integration_test(
    name="integrationtests",
    srcs=glob(["src/**/*.java"])
)